INSERT INTO
    sticky_notes(
        `id`,
        `uid`,
        `value`,
        `x`,
        `y`,
        `width`,
        `height`
    )
VALUES
    (
        1,
        "test",
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"golang","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
        200,
        100,
        "300px",
        "400px"
    );

INSERT INTO
    sticky_notes(
        `id`,
        `uid`,
        `value`,
        `x`,
        `y`,
        `width`,
        `height`
    )
VALUES
    (
        2,
        "test",
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"golang","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
        100,
        10,
        "300px",
        "400px"
    );