FROM golang:1.18.3-alpine as dev

ENV ROOT=/go/src/app
ENV CGO_ENABLED 0
WORKDIR ${ROOT}

COPY ./go/go.mod ./go/go.sum ./

RUN apk update && apk add git && go mod download && go install github.com/cosmtrek/air@latest

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]